# Generated by Django 4.0.1 on 2022-01-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=30)),
                ('room_number', models.CharField(max_length=5)),
                ('profile_image', models.ImageField(blank=True, upload_to='teacher_profile_images')),
                ('subjects_taught', models.ManyToManyField(related_name='teachers', to='teacher.Subject')),
            ],
        ),
    ]
